sensors:
#  depth_camera_0:
#    type: depth_camera
#    pose:
#      xyz: [3.082385, 1.750927, 1.82]
#      rpy: [0, 'pi/2', 0]
  logical_camera_0: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [ -0.05, 3, 1.92 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_1: # over the 4 bins at the top left
    type: logical_camera
    pose:
      xyz: [5.07, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_2:  # over the 4 bins at the bottom left
    type: logical_camera
    pose:
      xyz: [ 2.99, 1.750927, 1.82 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_3: # over the 4 bins at the top right
    type: logical_camera
    pose:
      xyz: [ 5.07, -1.750927, 1.82 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_4: # over the 4 bins at the bottom right
    type: logical_camera
    pose:
      xyz: [ 2.99, -1.750927, 1.82 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]


#  laser_profiler_0:
#    type: laser_profiler
#    pose:
#      xyz: [0., 1.486, 1.526]
#      rpy: ['pi/2', 'pi/2', 0]

#  range_finder_0:
#    type: proximity_sensor
#    pose:
#      xyz: [0, 2.840000, 0.970000]
#      rpy: [1.570796, 0.524365, 1.570796]

#  breakbeam_0:
#    type: break_beam
#    pose:
#      xyz: [-0.004795, 4.492549, 0.879306]
#      rpy: [0, 0, -1.557900]

  logical_camera_5: # over bottom middle shelf
    type: logical_camera
    pose:
      xyz: [-15.6241, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_6: # over bottom middle shelf
    type: logical_camera
    pose:
      xyz: [ -13.56, 0, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_7: # over bottom left shelf
    type: logical_camera
    pose:
      xyz: [ -15.6241, 3.05, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_8: # over bottom left shelf
    type: logical_camera
    pose:
      xyz: [ -13.56, 3.05, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_9: # over bottom right shelf
    type: logical_camera
    pose:
      xyz: [ -15.6241, -3.02, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_10: # over bottom right shelf
    type: logical_camera
    pose:
      xyz: [ -13.56, -3.02, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_11: # over top right shelf
    type: logical_camera
    pose:
      xyz: [ 5.07, -3.62, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_12: # over top right shelf
    type: logical_camera
    pose:
      xyz: [ 3, -3.62, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_13: # over top left shelf
    type: logical_camera
    pose:
      xyz: [ 5.07, 3.62, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_14: # over top left shelf
    type: logical_camera
    pose:
      xyz: [ 3, 3.62, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]
